### ISSUE TITLE
Use anchors

### ISSUE THREAD

**Issue by RosaWagner** [coreyhu/Urbanist#28]
Sorry I haven't spotted it earlier, your design is missing anchors, preventing from generating a proper mark_to_mark feature. This feature allow combination of accents for non-encoded letters. you can add them with `cmd+u` in glyphs. Then make sure your accented letters have automatic alignment, and adjust positon of accents by moving the anchors.

the tuto is pretty straightfoward : https://glyphsapp.com/learn/diacritics

**Comment by coreyhu** [comment]
Anchors should now be added and used for diacritic alignments. I made sure to tune them but feel free to let me know if anything looks out of place
