### ISSUE TITLE
Turkish letter support

### ISSUE THREAD

**Issue by sarptekbas** [coreyhu/Urbanist#31]
Hello,
Liked this font so much, I want to use it on my website. But I can't use it because there is no support for Turkish letters. Can you please add Turkish letters like İ, Ğ, Ü, Ş, Ç, Ö, ğ, ü, ş, ç, ö?

**Comment by coreyhu** [comment]
Thanks, would love to make this happen. I’ll add it to my todos

**Comment by sarptekbas** [comment]
Thank you @coreyhu for adding support for Turkish letters.
