### ISSUE TITLE
Kerning between i and x

### ISSUE THREAD

**Issue by coffeeandpixels** [coreyhu/Urbanist#45]
There is too much space between “i” and “x”. Try the word, “Pixels”.

**Comment by coreyhu** [comment]
Hi, thanks for raising this issue. This was due to a mistake with the spacing on the right side of the Black i (see #33) and should be fixed in PR #34. You can download the update in [the latest release](https://github.com/coreyhu/Urbanist/releases).

**Comment by coffeeandpixels** [comment]
Thank you for your reply, and for your hard work. Any idea when the latest version will be on Google Fonts?

**Comment by coreyhu** [comment]
Looks like GF has updated to the latest version (1.303), so I'll be closing this issue
