### ISSUE TITLE
"B" capital not smooth curve

### ISSUE THREAD

**Issue by carlos-villalba** [coreyhu/Urbanist#46]
Hey Corey,

I found a not smooth curve in the capital "B".
It is seen more in Bold, ExtraBold and Black.
Attached capture.

Cheers.
Carlos.

<img width="582" alt="Captura de pantalla 2021-12-16 a las 11 16 34" src="https://user-images.githubusercontent.com/63908598/146353448-88ebb65e-2eea-4b65-9413-173f1365a117.png">

**Comment by coreyhu** [comment]
Thanks, that's a good catch. I'll work on smoothing this out.
