### ISSUE TITLE
Degree symbol is not displayed correctly

### ISSUE THREAD

**Issue by srpolp** [coreyhu/Urbanist#60]
The degree symbol is not displayed correctly -> '60o'
I don't mean the glyphs.
60ª
60º

Thanks for your work

**Comment by coreyhu** [comment]
Hey this should be fixed in #53. Assuming you're using the version hosted on Google Fonts or elsewhere, can you download [the latest from releases](https://github.com/coreyhu/Urbanist/releases/latest) and verify whether this is still an issue?

**Comment by srpolp** [comment]
Thanks a lot Corey, it's fixed. But in Google fonts, at least in the test text it doesn't seem resolved.

In any case, perfect!

**Comment by bbdapereira** [comment]
Hi!
I'm facing this problem again in the 1.330 release.
Thank you for this awesome work!
